### ISSUE TITLE
Cannot install any extensions

### ISSUE THREAD

**Issue by Parv-Joshi** [microsoft/vsmarketplace#1080]
I installed VS Code latest version on my Windows 11 today and apprantly it cannot install any extensions. I tried to debug it using help using ChatGPT and other online resources, but nothing worked.
I was able to rule out DNS/Proxy issues, but it still seems Network related. Seems like it cannot connect to some of the Microsoft services. 

Note: if I try downloading mannually, I can do it usin VSIX, but it doesn't work through VS Code -- by click the install button or using terminal with extension ID).

Here is the output for one of the tries that show the issue:
2024-12-03 16:16:49.221 [warning] Settings pattern "issueReporter.*" doesn't match any settings
2024-12-03 16:16:49.222 [warning] Settings pattern "application.*" doesn't match any settings
2024-12-03 16:16:49.283 [info] Started local extension host with pid 13996.
2024-12-03 16:16:49.459 [info] Settings Sync: Updating due to initialize
2024-12-03 16:16:49.459 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-03 16:16:49.459 [info] Settings Sync: Authentication providers updated []
2024-12-03 16:16:49.667 [warning] Settings pattern "GitHub.copilot.manageExtension" doesn't match any settings
2024-12-03 16:16:50.149 [warning] Settings pattern "issueReporter.*" doesn't match any settings
2024-12-03 16:16:50.149 [warning] Settings pattern "application.*" doesn't match any settings
2024-12-03 16:16:51.513 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-03 16:16:51.513 [info] Settings Sync: Authentication providers updated ["github"]
2024-12-03 16:16:51.513 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-03 16:16:51.513 [info] Settings Sync: Authentication providers updated ["github"]
2024-12-03 16:16:51.513 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-03 16:16:51.514 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-03 16:16:51.514 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-03 16:16:51.514 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-03 16:16:51.532 [info] Settings Sync: Updating due to declared authentication providers changed
2024-12-03 16:16:51.532 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-03 16:16:51.532 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-03 16:16:51.532 [info] Settings Sync: Updating due to declared authentication providers changed
2024-12-03 16:16:51.532 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-03 16:16:51.532 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-03 16:16:52.102 [warning] Settings pattern "application.*" doesn't match any settings
2024-12-03 16:16:52.277 [warning] Settings pattern "GitHub.copilot.manageExtension" doesn't match any settings
2024-12-03 16:16:53.144 [warning] Settings pattern "GitHub.copilot.manageExtension" doesn't match any settings
2024-12-03 16:16:53.936 [info] [perf] Render performance baseline is 16ms
2024-12-03 16:16:54.309 [warning] Settings pattern "application.*" doesn't match any settings
2024-12-03 16:16:55.343 [warning] Settings pattern "GitHub.copilot.manageExtension" doesn't match any settings
2024-12-03 16:17:12.313 [error] [network] #3: https://github.gallerycdn.vsassets.io/extensions/github/copilot/1.246.0/1732629269344/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:17:12.576 [error] [network] #4: https://github.gallerycdn.vsassets.io/extensions/github/copilot/1.246.0/1732629269344/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:17:13.222 [error] [network] #6: https://github.gallerycdn.vsassets.io/extensions/github/copilot/1.246.0/1732629269344/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:17:14.814 [error] [network] #5: https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
2024-12-03 16:17:14.814 [warning] Failed to fetch chat participant registry Failed to fetch
2024-12-03 16:17:15.362 [error] [network] #9: https://github.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.246.0/assetbyname/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:17:33.527 [error] [network] #11: https://github.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.246.0/assetbyname/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:17:33.644 [error] [network] #12: https://github.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.246.0/assetbyname/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:17:43.991 [error] [network] #14: https://amazonwebservices.gallerycdn.vsassets.io/extensions/amazonwebservices/aws-toolkit-vscode/3.37.0/1733237498849/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:17:43.992 [error] [network] #15: https://amazonwebservices.gallerycdn.vsassets.io/extensions/amazonwebservices/aws-toolkit-vscode/3.37.0/1733237498849/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:17:44.229 [error] [network] #17: https://amazonwebservices.gallery.vsassets.io/_apis/public/gallery/publisher/AmazonWebServices/extension/aws-toolkit-vscode/3.37.0/assetbyname/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:17:44.230 [error] TypeError: Failed to fetch
    at i$s (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:35915)
    at vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:37096
    at prt.c (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:494:27265)
    at prt.request (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:37088)
    at n9e.G (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1316:167)
    at async n9e.getManifest (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1314:41808)
    at async eF.zb (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2367:9069)
    at async eF.setInput (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2367:6061)
    at async j8e.U (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:663:100849)
    at async j8e.M (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:663:99400)
2024-12-03 16:18:05.186 [error] [network] #16: https://amazonwebservices.gallery.vsassets.io/_apis/public/gallery/publisher/AmazonWebServices/extension/aws-toolkit-vscode/3.37.0/assetbyname/Microsoft.VisualStudio.Code.Manifest - error GET Failed to fetch
2024-12-03 16:18:05.218 [error] TypeError: Failed to fetch
    at i$s (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:35915)
    at vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:37096
    at prt.c (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:494:27265)
    at prt.request (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:37088)
    at n9e.G (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1316:167)
    at async n9e.getManifest (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1314:41808)
    at async Brt.X (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3095:9120)
    at async Brt.installFromGallery (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3095:5991)
    at async vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2433:34619
2024-12-03 16:18:05.220 [error] Failed to fetch: TypeError: Failed to fetch
    at i$s (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:35915)
    at vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:37096
    at prt.c (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:494:27265)
    at prt.request (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:37088)
    at n9e.G (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1316:167)
    at async n9e.getManifest (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1314:41808)
    at async Brt.X (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3095:9120)
    at async Brt.installFromGallery (vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3095:5991)
    at async vscode-file://vscode-app/c:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2433:34619
2024-12-03 16:18:27.496 [info] Settings Sync: Updating authentication providers. Authentication Providers from store: [{"id":"github","scopes":["user:email"]},{"id":"microsoft","scopes":["openid","profile","email","offline_access"]}]
2024-12-03 16:18:27.496 [info] Settings Sync: Authentication providers updated ["github","microsoft"]
2024-12-03 16:18:27.562 [error] [uncaught exception in main]: Titlebar overlay is not enabled: Error: Titlebar overlay is not enabled
    at bu.updateWindowControls (file:///C:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:71:49285)
    at bu.n (file:///C:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:71:47098)
    at bu.Q (file:///C:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:80:8705)
    at bu.tryClaimWindow (file:///C:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:80:8475)
    at App.<anonymous> (file:///C:/Users/Parv/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/main.js:80:9718)
    at App.emit (node:events:519:28)
    at n._init (node:electron/js2c/browser_init:2:12818)
    at openGuestWindow (node:electron/js2c/browser_init:2:101599)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89067)
    at WebContents.emit (node:events:519:28)

**Comment by madhurivadaligithub** [comment]
Hi @Parv-Joshi ,

Thanks for reaching out to VS Marketplace Team. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
