### ISSUE TITLE
python

### ISSUE THREAD

**Issue by Gramatik92** [microsoft/vsmarketplace#329]
Hello i want to instal Python extension and it says: 

Error while installing 'Python Extension Pack' extension. Please check the [log](command:workbench.action.showWindowLog) for more details. and [2022-02-09 16:04:15.404] [renderer1] [info] IExtensionHostStarter.start() took 604 ms.
[2022-02-09 16:04:15.971] [renderer1] [error] [Extension Host] (node:8712) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-02-09 16:04:55.504] [renderer1] [error] ["Invalid: Corrupt ZIP: end of central directory record signature not found","    at D.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)","    at async D.doRun (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)"]
[2022-02-09 16:04:55.562] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at D.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)
    at async D.doRun (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)
[2022-02-09 16:10:25.823] [renderer1] [error] ["Invalid: Corrupt ZIP: end of central directory record signature not found","    at D.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)","    at async D.doRun (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)"]
[2022-02-09 16:10:25.904] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at D.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)
    at async D.doRun (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)
[2022-02-09 16:11:07.355] [renderer1] [error] ["Invalid: Corrupt ZIP: end of central directory record signature not found","    at D.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)","    at async D.doRun (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)"]
[2022-02-09 16:11:07.432] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at D.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)
    at async D.doRun (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)
[2022-02-09 16:12:14.481] [renderer1] [error] ["Invalid: Corrupt ZIP: end of central directory record signature not found","    at D.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)","    at async D.doRun (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)"]
[2022-02-09 16:12:14.553] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at D.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:222791)
    at async D.doRun (vscode-file://vscode-app/c:/Users/mobynm/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:221269)

if i manually download it then it say:  Corrupt ZIP: end of central directory record signature not found

**Comment by Gramatik92** [comment]
Sorry, so the problem is, i want to instal python extension in VSC and thats the problem...

**Comment by pratikgawali-msft** [comment]
@isidorn since the issue is while installing the python extension on VS Code, could you please guide here?
If this is an issue with the python package, we could reach out to https://github.com/Microsoft/vscode-python.

Meanwhile, @Gramatik92 could you please confirm if you are still facing this issue because I am able to install the extension without facing any error?

**Comment by SaiKanth007** [comment]
@Gramatik92 Since we haven't heard anything from you, we assume this is fixed. We are closing this ticket for now, feel free to open a new ticket if you are facing any other issue.
