### ISSUE TITLE
workbench.desktop.main.js:810 Extension host terminated unexpectedly 3 times within the last 5 minutes.

### ISSUE THREAD

**Issue by mkiowser** [microsoft/vsmarketplace#470]
my extensions can not work; here is two errors :
-------------------------------------------------------------------------------
## Fatal error in , line 0# Fatal JavaScript invalid size error 174895934####FailureMessage Object: 00000064A8BFD310 1: 00007FF65470D2ED node_api_get_module_file_name+18429 2: 00007FF6577A73AE Cr_z_zError+1660654 3: 00007FF6556A8D2B uv_random+5694443 4: 00007FF6537285D6 v8::CppHeap::GetAllocationHandle+523590 5: 00007FF656F60E1B v8::Platform::SystemClockTimeMillis+200507 6: 00007FF6537A49DA v8::internal::OSROptimizedCodeCache::TryGet+171914 7: 00007FF5D7ECC93C 

-------------------------------------------------------------------------------

 WebSocket is not open: readyState 3 (CLOSED): Error: WebSocket is not open: readyState 3 (CLOSED)
    at sendAfterClose (D:\program\vscode\Microsoft VS Code\resources\app\node_modules.asar\ws\lib\websocket.js:763:17)
    at WebSocket.send (D:\program\vscode\Microsoft VS Code\resources\app\node_modules.asar\ws\lib\websocket.js:345:7)
    at Chrome._enqueueCommand (D:\program\vscode\Microsoft VS Code\resources\app\node_modules.asar\chrome-remote-interface\lib\chrome.js:281:18)
    at D:\program\vscode\Microsoft VS Code\resources\app\node_modules.asar\chrome-remote-interface\lib\chrome.js:87:22
    at new Promise (<anonymous>)
    at Chrome.send (D:\program\vscode\Microsoft VS Code\resources\app\node_modules.asar\chrome-remote-interface\lib\chrome.js:86:20)
    at Object.handler [as stop] (D:\program\vscode\Microsoft VS Code\resources\app\node_modules.asar\chrome-remote-interface\lib\api.js:32:23)
    at Object.stop (D:\program\vscode\Microsoft VS Code\resources\app\node_modules.asar\v8-inspect-profiler\index.js:97:41)
    at n.stopProfiling (vscode-file://vscode-app/d:/program/vscode/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:31:56313)
    at Object.call (vscode-file://vscode-app/d:/program/vscode/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:24:8427)
    at a.onPromise (vscode-file://vscode-app/d:/program/vscode/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:23:5869)
    at a.onRawMessage (vscode-file://vscode-app/d:/program/vscode/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:23:5245)
    at vscode-file://vscode-app/d:/program/vscode/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:23:4526
    at S.invoke (vscode-file://vscode-app/d:/program/vscode/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:145)
    at g.deliver (vscode-file://vscode-app/d:/program/vscode/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:2266)
    at C.fire (vscode-file://vscode-app/d:/program/vscode/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:19:1844)
    at MessagePort.Z (vscode-file://vscode-app/d:/program/vscode/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:17:23639)

**Comment by madhurivadaligithub** [comment]
Hi @mkiowser The issue was related to vs code.
Please create your issue here https://github.com/microsoft/vscode/issues
