### ISSUE TITLE
failed to install python extension in Jetson agx orin

### ISSUE THREAD

**Issue by WYYAHYT** [microsoft/vsmarketplace#508]
Type: <b>Bug</b>

I tried to install **python extension** in **Jetson agx orin**, but always failed, bug report below:
```
error 10:20:22.42: Failed to install Python Extension via Kernel Picker command
warn 10:20:22.45: DataScience Error [Error: Failed to install the Python Extension.
	at _.installPythonExtensionViaKernelPicker (/home/orin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.8.1002431052/out/extension.node.js:2:2407793)
	at async a._executeContributedCommand (/home/orin/.vscode-server-insiders/bin/da76f93349a72022ca4670c1b84860304616aaa2/out/vs/workbench/api/node/extensionHostProcess.js:85:63914)]

```

VS Code version: Code - Insiders 1.70.0-insider (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-03T05:53:23.899Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux arm64 5.10.65-tegra
Remote OS version: Linux x64 4.15.0-176-generic

**Comment by madhurivadaligithub** [comment]
Hi @WYYAHYT if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues
