### ISSUE TITLE
Not able to install any extension 

### ISSUE THREAD

**Issue by Aerofarmer** [microsoft/vsmarketplace#541]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Aerofarmer** [comment]
Type: <b>Bug</b>

t Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:769:26471)
2022-12-21 12:31:50.517 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:31:50.782 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:31:50.826 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:31:51.020 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:31:51.204 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:31:52.140 [info] [perf] Render performance baseline is 30ms
2022-12-21 12:31:55.355 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:31:55.380 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:31:55.396 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:31:55.397 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:31:59.960 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:32:00.008 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:32:33.458 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:32:33.511 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:33:03.288 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:33:08.131 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:33:08.215 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:33:16.257 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:33:16.310 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:35:03.730 [warning] Settings pattern "keyboard.*" doesn't match any settings
2022-12-21 12:35:03.780 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:37:09.694 [warning] Settings pattern "keyboard.*" doesn't match any settings
2022-12-21 12:37:57.942 [warning] Settings pattern "keyboard.*" doesn't match any settings
2022-12-21 12:38:09.197 [warning] Settings pattern "keyboard.*" doesn't match any settings
2022-12-21 12:38:11.762 [warning] Settings pattern "keyboard.*" doesn't match any settings
2022-12-21 12:38:19.680 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:38:19.717 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:38:40.416 [warning] Settings pattern "keyboard.*" doesn't match any settings
2022-12-21 12:38:54.892 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:38:54.892 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:40:15.731 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:40:15.732 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:40:18.769 [warning] Settings pattern "keyboard.*" doesn't match any settings
2022-12-21 12:40:21.325 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:40:21.326 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:40:22.131 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:40:22.132 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:40:22.729 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:40:22.729 [info] Setting search error: Unexpected token : in JSON at position 22710
2022-12-21 12:40:33.730 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:40:33.778 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:46:02.657 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:46:02.690 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:47:21.610 [warning] Editor ID Mismatch: default !== workbench.editorinputs.sidebysideEditorInput. This will cause bugs. Please ensure editorInput.editorId matches the registered id
2022-12-21 12:47:21.819 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:48:33.695 [error] SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)
2022-12-21 12:48:33.762 [error] Unexpected token : in JSON at position 22710: SyntaxError: Unexpected token : in JSON at position 22710
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Amrit.Sharma.ext/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:91783)


VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
Hi @Aerofarmer This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues

**Comment by isidorn** [comment]
Maybe duplicate of https://github.com/microsoft/vscode/issues/172989
Please file an issue in GitHub repo as Madhuri suggests

fyi @sandy081
