### ISSUE TITLE
Unable to Install Extensions

### ISSUE THREAD

**Issue by Justin-Willson** [microsoft/vsmarketplace#574]
Type: <b>Bug</b>

Steps to reproduce
On a fresh install of Visual Studio Code 1.75.0 x64, attempt to install an extension. Error persists even when running "--install-extension extension_name.visx" from command line.

Attempting to install an extension gives the following error messages:
2023-02-03 10:46:51.017 [error] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Justin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:93520)
2023-02-03 10:46:51.101 [error] Unexpected end of JSON input: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.factory (vscode-file://vscode-app/c:/Users/Justin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:88:93520)

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @Justin-Willson  This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
