### ISSUE TITLE
开启vpn后，无法安装插件

### ISSUE THREAD

**Issue by Paradox315** [microsoft/vsmarketplace#612]
Type: <b>Bug</b>

开启clash的系统代理后，可以浏览搜索扩展市场，但是当点击安装时，出现以下报错，提示无法安装
2023-03-09 20:50:13.844 [error] net::ERR_CONNECTION_CLOSED: Download: net::ERR_CONNECTION_CLOSED
    at yt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:90:157025)
    at async X.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)

VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

**Comment by SaiKanth007** [comment]
This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
