### ISSUE TITLE
Unable to update or download extensions "Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'

### ISSUE THREAD

**Issue by acchhhoooo** [microsoft/vsmarketplace#732]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.79.2
- OS Version: Mac OS 13.4.1 (c) 

Steps to Reproduce:

1. Downloading/updating certain extensions eg docker, powershell
2. No issue if using VSCode Insiders

Error in terminal when clicking the update:
[error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at gt.download (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:82:141)
    at async j.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:82:20937)
    at async j.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:82:19006)

Clicking on the error log, it shows the following:
{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}

**Comment by madhurivadaligithub** [comment]
Thank you for reporting your concern. We are following up to determine how best to address it.

Thanks,
VS Marketplace Team

**Comment by acchhhoooo** [comment]
Thank you. But why was the issue moved to vsmarketplace?

**Comment by acchhhoooo** [comment]
Hi, any updates? Cos I'm still experiencing the issues

**Comment by megretson** [comment]
I may be experiencing the same issue as above, or the error message may not be specific enough for me to correctly triage my problem:
VS Code Version 1.8.0
OS version: SUSE Linux Enterprise Server 15 SP4

Steps to reproduce:
1. Go to extensions, select update for "Extension Pack for Java" 
2. "Error while updating 'Extension Pack for Java' extension. Please check the log for more details" 
`2023-08-01 13:30:39.946 [error] [Extension Host] (node:48852) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `exe --trace-warnings ...` to show where the warning was created)
2023-08-01 13:30:39.953 [error] Error: ENOENT: no such file or directory, scandir '/<my home directory>/.config/Code/User/workspaceStorage/d90cda08e5dea6202431e478b61a6be0/redhat.java': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, scandir '/<my home directory>/.config/Code/User/workspaceStorage/d90cda08e5dea6202431e478b61a6be0/redhat.java'
	at ii.e (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:26766)
	at Object.readDirectory (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:24764)
2023-08-01 13:30:41.049 [info] [perf] Render performance baseline is 50ms
2023-08-01 13:30:41.696 [error] net::ERR_CERT_AUTHORITY_INVALID: Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-08-01 13:31:07.183 [error] Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-08-01 13:31:07.335 [error] net::ERR_CERT_AUTHORITY_INVALID: Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-08-01 13:31:27.764 [error] Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-08-01 13:31:27.795 [error] net::ERR_CERT_AUTHORITY_INVALID: Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-08-01 13:37:18.357 [error] Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-08-01 13:37:18.388 [error] net::ERR_CERT_AUTHORITY_INVALID: Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49312)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)`
3. Select "Try Downloading Manually..." 
`{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}`

**Comment by acchhhoooo** [comment]
hi, any updates?

**Comment by neo-lift** [comment]
I have experienced the same issue on windows 11 for vscode 1.8.1. I have tried to reinstall vscode many times but didn't get any lucky.

**Comment by Raquel-VF** [comment]
I'm having this same problem, I can not install any extension, I've searched for everything and find no solution

**Comment by ahmedmansoor** [comment]
same issue here

**Comment by katiejim** [comment]
myself and a colleague are also experiencing similar issues!

- When trying to install some extensions (e.g. for Jupyter and Python) from within VSCode, we get the error: "CorruptZip: end of central directory record signature not found". However, some extensions install without issue (e.g. indent-rainbow by oderwat). 

- For extensions that encounter the CorruptZip error, we have tried clearing our cached content from relevant VSCode folders (found in C:\Users\<user>\AppData\Roaming\Code\) - including the folders CachedExtensionVSIXs and CachedData as outlined in the Stackoverflow solution [here](https://stackoverflow.com/questions/41530269/error-end-of-central-directory-record-signature-not-found-while-installing-ion) - but still get the same CorruptZip error

- When trying to manually install the VSIX files from online as prompted, we intermittently get the error "request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'"

Any advice on this issue would be hugely appreciated! Thank you

**Comment by katiejim** [comment]
@Raquel-VF @ahmedmansoor @neo-lift @acchhhoooo 

if any of you are still having trouble with this, we have found a fix that has worked for us:

1. go to the path C:\Users\<username>\AppData\Roaming\Code and delete the folders 'CachedProfilesData', 'CachedData', and 'CachedExtensionVSIXs'. Close and re-open VSCode

2. try to install the desired extension - step 1 above may have cleared out any corrupted extension files and could have solved the installation problem	

3. if the extension installation still fails, follow the prompt from the pop-up window in VSCode to try downloading the VSIX file from the marketplace web address. If you hit the "Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'" error, keep trying to access the link. we tried refreshing the page at ten minute intervals and finally a VSIX file began to download

4. move the extension VSIX file from your downloads into the folder C:\Users\<username>\.vscode\extensions. Then, using the prompts in the VSCode popup or via the command line, load the extension into VSCode from the VSIX file. 

really hope this works for you all!

**Comment by Raquel-VF** [comment]
Thank you, I installed insiders and it works perfectly. and it's even lighter

**Comment by AngborTim** [comment]
I have the same issue. When I try to install any extension I get "The editor could not be opened due to an unexpected error: XHR failed"
Deleting 'CachedProfilesData', 'CachedData' didn't bring any changes. And I didn't find 'CachedExtensionVSIXs'

**Comment by TranSyLongTrangThi** [comment]
My solution is uninstall VSCode and delete folders CachedExtensionVSIXs and CachedData (C:\Users{user}\AppData\Roaming\Code), then download the VSCode again.

**Comment by dmitry1100** [comment]
I downloaded it! When I clicked Try Download Manually and got this message, I copied page URL, it was: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dotnettools/vsextensions/csharp/2.13.10/vspackage?targetPlatform=darwin-arm64
So, I got keywords from it: ms-dotnettools vsextensions csharp 2.13.10 and searched them in web. So, I found an extension page in the marketplace. There is a tab "Version History" where I found a link for my architecture and that link worked well to download the extension manually.

**Comment by maietta** [comment]
Dealing with this issue. I've been struggling to get access to the marketplace for a while. Seems like I have to hit refresh about a dozen times before it finally loads.

I thought perhaps it was a DNS issue, but the same issue happens on all DNS servers I tried.

**Comment by amorimds** [comment]
I was having the same problem. I think it was being caused by my company's VPN: After turning it off I was able to download and install the extension.

I hope that helps!

**Comment by Elizabeth-CR** [comment]
> I was having the same problem. I think it was being caused by my company's VPN: After turning it off I was able to download and install the extension.
> 
> I hope that helps!

I came across the same problem this afternoon at work and it was indeed the company's VPN.  A moment ago I experienced the same problem on my personal computer, this time due to the antivirus extension, and after disabling it I was able to download the Docker extension on VS Code without problems. Thanks a lot!!
