### ISSUE TITLE
Error while installing 'Material Icon Theme' extension. Please check the log for more details.

### ISSUE THREAD

**Issue by zsdx1524** [microsoft/vsmarketplace#782]
I tried to download the app from the vscode, but I get this error

2023-10-09 14:24:10.508 [error] Bad escaped character in JSON at position 180: SyntaxError: Bad escaped character in JSON at position 180
    at JSON.parse (<anonymous>)
    at Object.factory (c:\Users\송진영\scoop\apps\vscode\1.83.0\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:99:85837)
2023-10-09 14:24:10.516 [error] SyntaxError: Bad escaped character in JSON at position 180
    at JSON.parse (<anonymous>)
    at Object.factory (c:\Users\송진영\scoop\apps\vscode\1.83.0\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:99:85837)

**Comment by madhurivadaligithub** [comment]
Hi @zsdx1524 

Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
