### ISSUE TITLE
I cannot download extensions anymore.

### ISSUE THREAD

**Issue by jurebia** [microsoft/vsmarketplace#869]
Type: <b>Bug</b>

I cannot download extensions anymore.

Website https://marketplace blocked me out.
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/suntobright/vsextensions/vscode-sftp/1.1.1/vspackage

{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}

Log error:
2024-03-14 07:13:56.643 [error] CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at X.rb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:21229)
    at async X.qb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:20488)
    at async X.Ob (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2952:3799)
    at async X.jb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:18068)
2024-03-14 07:13:56.669 [error] No remote extension installed to resolve ssh-remote.: CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at X.rb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:21229)
    at async X.qb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:20488)
    at async X.Ob (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2952:3799)
    at async X.jb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:18068)

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'vscode-remote' could not be established  No remote extension installed to resolve ssh-remote.

**Comment by madhurivadaligithub** [comment]
Hi @jurebia 

Thank you for reaching VS Marketplace Team. We are looking into the issue and will get back to you with an update.

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @jurebia 

As you are hitting global Azure DevOps limits [Rate and usage limits - Azure DevOps | Microsoft Learn](https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops), could you please wait and will be able to download again.

Meanwhile can you please share your scenario and how you are getting into this issue?

-Regards,
VS Marketplace Team
