### ISSUE TITLE
I cannot download extensions anymore.

### ISSUE THREAD

**Issue by jurebia** [microsoft/vsmarketplace#870]
Type: <b>Bug</b>

I cannot download extensions anymore.

Website https://marketplace blocked me out.
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/suntobright/vsextensions/vscode-sftp/1.1.1/vspackage

{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}

Log error:
2024-03-14 07:13:56.643 [error] CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at X.rb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:21229)
    at async X.qb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:20488)
    at async X.Ob (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2952:3799)
    at async X.jb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:18068)
2024-03-14 07:13:56.669 [error] No remote extension installed to resolve ssh-remote.: CodeExpectedError: No remote extension installed to resolve ssh-remote.
    at X.rb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:21229)
    at async X.qb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:20488)
    at async X.Ob (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2952:3799)
    at async X.jb (vscode-file://vscode-app/c:/Users/kri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2950:18068)

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'vscode-remote' could not be established  No remote extension installed to resolve ssh-remote.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (2.46GB free)|
|Process Argv|--crash-reporter-id bc0a07d0-e340-4605-80bf-1b408f28c8db|
|Screen Reader|no|
|VM|0%|

Connection to 'vscode-remote' could not be established  No remote extension installed to resolve ssh-remote.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30958156
dsvsc020:30976470

```

</details>

**Comment by madhurivadaligithub** [comment]
tracking here https://github.com/microsoft/vsmarketplace/issues/869
