### ISSUE TITLE
remote-ssh

### ISSUE THREAD

**Issue by xuzhou2016** [microsoft/vsmarketplace#879]
Type: <b>Bug</b>

I cannot connect to remote linux server via remote-ssh at recent version. 
Please help me.
thanks

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 6.1.32-amd64-desktop-hwe
Modes:
Connection to 'SSH' could not be established

**Comment by xuzhou2016** [comment]
[22:37:26.656] Log Level: 2
[22:37:26.714] SSH Resolver called for "ssh-remote+110.40.174.70", attempt 1
[22:37:26.714] "remote.SSH.useLocalServer": true
[22:37:26.714] "remote.SSH.useExecServer": true
[22:37:26.720] "remote.SSH.path": undefined
[22:37:26.720] "remote.SSH.configFile": undefined
[22:37:26.721] "remote.SSH.useFlock": true
[22:37:26.721] "remote.SSH.lockfilesInTmp": false
[22:37:26.721] "remote.SSH.localServerDownload": auto
[22:37:26.721] "remote.SSH.remoteServerListenOnSocket": false
[22:37:26.721] "remote.SSH.showLoginTerminal": false
[22:37:26.721] "remote.SSH.defaultExtensions": []
[22:37:26.721] "remote.SSH.loglevel": 2
[22:37:26.721] "remote.SSH.enableDynamicForwarding": true
[22:37:26.722] "remote.SSH.enableRemoteCommand": false
[22:37:26.722] "remote.SSH.serverPickPortsFromRange": {}
[22:37:26.722] "remote.SSH.serverInstallPath": {}
[22:37:26.733] VS Code version: 1.87.2
[22:37:26.733] Remote-SSH version: remote-ssh@0.109.0
[22:37:26.733] linux x64
[22:37:26.735] SSH Resolver called for host: 110.40.174.70
[22:37:26.735] Setting up SSH remote "110.40.174.70"
[22:37:26.750] Acquiring local install lock: /tmp/vscode-remote-ssh-56dd6708-install.lock
[22:37:26.754] Looking for existing server data file at /home/ubuntu/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-56dd6708-863d2581ecda6849923a2118d93a088b0745d9d6-0.109.0-es/data.json
[22:37:26.759] Using commit id "863d2581ecda6849923a2118d93a088b0745d9d6" and quality "stable" for server
[22:37:26.786] Install and start server if needed
[22:37:26.802] PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin
[22:37:26.802] Checking ssh with "ssh -V"
[22:37:26.849] > OpenSSH_9.6p1 Deepin, OpenSSL 3.0.12 24 Oct 2023

[22:37:26.862] askpass server listening on /run/user/1000/vscode-ssh-askpass-d62a0d8d5e6433997c9a3cf85d7470012d10efd5.sock
[22:37:26.862] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-8ace08518da5871a598ac9412779dfc53e8c9188.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42587","-o","ConnectTimeout=15","110.40.174.70"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/ubuntu/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-56dd6708-863d2581ecda6849923a2118d93a088b0745d9d6-0.109.0-es/data.json"}
[22:37:26.862] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/apps/com.visualstudio.code/files/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-d62a0d8d5e6433997c9a3cf85d7470012d10efd5.sock"}
[22:37:26.866] Spawned 21244
[22:37:27.113] > local-server-1> Running ssh connection command: ssh -v -T -D 42587 -o ConnectTimeout=15 110.40.174.70
[22:37:27.132] > local-server-1> Spawned ssh, pid=21253
[22:37:27.139] stderr> OpenSSH_9.6p1 Deepin, OpenSSL 3.0.12 24 Oct 2023
[22:37:27.139] stderr> /home/ubuntu/.ssh/config: line 3: Bad configuration option: user:
[22:37:27.139] stderr> /home/ubuntu/.ssh/config: line 4: Bad configuration option: identityfile:
[22:37:27.139] stderr> /home/ubuntu/.ssh/config: terminating, 2 bad configuration options
[22:37:27.141] > local-server-1> ssh child died, shutting down
[22:37:27.150] Local server exit: 0
[22:37:27.152] Received install output: local-server-1> Running ssh connection command: ssh -v -T -D 42587 -o ConnectTimeout=15 110.40.174.70
local-server-1> Spawned ssh, pid=21253
OpenSSH_9.6p1 Deepin, OpenSSL 3.0.12 24 Oct 2023
/home/ubuntu/.ssh/config: line 3: Bad configuration option: user:
/home/ubuntu/.ssh/config: line 4: Bad configuration option: identityfile:
/home/ubuntu/.ssh/config: terminating, 2 bad configuration options
local-server-1> ssh child died, shutting down

[22:37:27.167] Failed to parse remote port from server output
[22:37:27.173] Resolver error: Error: 
	at g.Create (/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:499734)
	at t.handleInstallOutput (/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:497056)
	at e (/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:558185)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:580094
	at async t.withShowDetailsEvent (/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:583753)
	at async /home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:554890
	at async T (/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:552941)
	at async t.resolveWithLocalServer (/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:554430)
	at async k (/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:577311)
	at async t.resolve (/home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:581124)
	at async /home/ubuntu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:847283
[22:37:27.182] ------

**Comment by madhurivadaligithub** [comment]
Hi @xuzhou2016 ,

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team

**Comment by a087228** [comment]
You might want to take a look at your config file.

`[22:37:27.139] stderr> /home/ubuntu/.ssh/config: line 3: Bad configuration option: user:
[22:37:27.139] stderr> /home/ubuntu/.ssh/config: line 4: Bad configuration option: identityfile:
[22:37:27.139] stderr> /home/ubuntu/.ssh/config: terminating, 2 bad configuration options`
