### ISSUE TITLE
Error while installing extensions in devcontainer 

### ISSUE THREAD

**Issue by g-kartik** [microsoft/vsmarketplace#885]
Type: <b>Bug</b>

Clone this repository
https://github.com/g-kartik/cvat/tree/devcontainer-for-development-environment
Open the branch in devcontainer
Some extensions are unable to install

Devcontainer logs
[464801 ms] [01:33:41] [127.0.0.1][9ca51f5f][ExtensionHostConnection] New connection established.
[464852 ms] [01:33:42] [127.0.0.1][9ca51f5f][ExtensionHostConnection] <1166> Launched Extension Host Process.
[465965 ms] [01:33:43] Installing extension 'ms-python.debugpy'...
[465984 ms] [01:33:43] Installing extension 'ms-python.python'...
[01:33:43] Installing extension 'dbaeumer.vscode-eslint'...
[466001 ms] [01:33:43] Installing extension 'ms-azuretools.vscode-docker'...
[01:33:43] Installing extension 'stylelint.vscode-stylelint'...
[466036 ms] [01:33:43] Installing extension 'esbenp.prettier-vscode'...
[466043 ms] [01:33:43] Installing extension 'ymotongpoo.licenser'...
[466061 ms] [01:33:43] Installing extension 'ms-vscode.js-debug'...
[466095 ms] [01:33:43] Installing extension 'streetsidesoftware.code-spell-checker'...
[466097 ms] [01:33:43] Installing extension 'shardulm94.trailing-spaces'...
[466100 ms] [01:33:43] Getting Manifest... ms-python.debugpy
[01:33:43] Getting Manifest... ms-python.python
[466101 ms] [01:33:43] Getting Manifest... dbaeumer.vscode-eslint
[01:33:43] Getting Manifest... ms-azuretools.vscode-docker
[01:33:43] Getting Manifest... stylelint.vscode-stylelint
[01:33:43] Getting Manifest... esbenp.prettier-vscode
[01:33:43] Getting Manifest... ymotongpoo.licenser
[01:33:43] Getting Manifest... ms-vscode.js-debug
[01:33:43] Getting Manifest... streetsidesoftware.code-spell-checker
[01:33:43] Getting Manifest... shardulm94.trailing-spaces
[467672 ms] [01:33:44] Installing extension: ms-python.debugpy
[01:33:44] Installing extension: dbaeumer.vscode-eslint
[01:33:44] Installing extension: stylelint.vscode-stylelint
[01:33:44] Installing extension: ms-python.python
[01:33:44] Installing extension: esbenp.prettier-vscode
[01:33:44] Installing extension: ms-azuretools.vscode-docker
[01:33:44] Installing extension: ymotongpoo.licenser
[01:33:44] Installing extension: shardulm94.trailing-spaces
[01:33:44] Installing extension: streetsidesoftware.code-spell-checker
[01:33:44] Installing extension: ms-vscode.js-debug
[469353 ms] [01:33:46] Getting Manifest... ms-python.python
[469544 ms] [01:33:46] Getting Manifest... ms-python.vscode-pylance
[469683 ms] [01:33:46] Getting Manifest... ms-python.debugpy
[469800 ms] [01:33:46] Installing extension: ms-python.vscode-pylance
[470287 ms] [01:33:47] Getting Manifest... ms-python.vscode-pylance
[471082 ms] [01:33:48] Error while installing the extension ms-vscode.js-debug Unable to write file '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json')
[472088 ms] rejected promise not handled within 1 second: UpdateMetadata: Unable to write file '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json')
[472092 ms] stack trace: UpdateMetadata: Unable to write file '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json')
    at se.x (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:173:82669)
    at async se.h (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:173:80430)
[472097 ms] [01:33:49] UpdateMetadata: Unable to write file '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json')
    at se.x (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:173:82669)
    at async se.h (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:173:80430) {
  code: 'UpdateMetadata'
}
[472828 ms] Start: Run in container: mkdir -p '/vscode/vscode-server/extensionsCache' && cd '/home/devcontainer/.vscode-server/extensionsCache' && cp 'ms-python.python-2024.4.1.sigzip' '/vscode/vscode-server/extensionsCache'
[472837 ms] 
[472838 ms] 
[472838 ms] Start: Run in container: cd '/vscode/vscode-server/extensionsCache' && ls -t | tail -n +50 | xargs rm -f
[472849 ms] 
[472850 ms] 
[514051 ms] [01:34:31] Extension signature is verified: shardulm94.trailing-spaces
[514069 ms] [01:34:31] Extension signature is verified: stylelint.vscode-stylelint
[514072 ms] [01:34:31] Extension signature is verified: ymotongpoo.licenser
[514072 ms] [01:34:31] Extension signature is verified: ms-azuretools.vscode-docker
[01:34:31] Extension signature is verified: esbenp.prettier-vscode
[01:34:31] Extension signature is verified: streetsidesoftware.code-spell-checker
[01:34:31] Extension signature is verified: ms-python.python
[514073 ms] [01:34:31] Extension signature is verified: dbaeumer.vscode-eslint
[514075 ms] [01:34:31] Extension signature is verified: ms-python.vscode-pylance
[514275 ms] [01:34:31] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/stylelint.vscode-stylelint-1.4.0: stylelint.vscode-stylelint
[514284 ms] [01:34:31] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.4: dbaeumer.vscode-eslint
[514298 ms] [01:34:31] Renamed to /home/devcontainer/.vscode-server/extensions/stylelint.vscode-stylelint-1.4.0
[514298 ms] [01:34:31] Renamed to /home/devcontainer/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.4
[514307 ms] [01:34:31] Extracting extension completed. stylelint.vscode-stylelint
[514307 ms] [01:34:31] Extracting extension completed. dbaeumer.vscode-eslint
[514529 ms] [01:34:31] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/shardulm94.trailing-spaces-0.4.1: shardulm94.trailing-spaces
[514553 ms] [01:34:31] Renamed to /home/devcontainer/.vscode-server/extensions/shardulm94.trailing-spaces-0.4.1
[514570 ms] [01:34:31] Extracting extension completed. shardulm94.trailing-spaces
[514695 ms] [01:34:31] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/ms-azuretools.vscode-docker-1.29.0: ms-azuretools.vscode-docker
[514712 ms] [01:34:31] Renamed to /home/devcontainer/.vscode-server/extensions/ms-azuretools.vscode-docker-1.29.0
[514722 ms] [01:34:31] Extracting extension completed. ms-azuretools.vscode-docker
[514772 ms] [01:34:31] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/esbenp.prettier-vscode-10.4.0: esbenp.prettier-vscode
[514778 ms] [01:34:31] Renamed to /home/devcontainer/.vscode-server/extensions/esbenp.prettier-vscode-10.4.0
[514786 ms] [01:34:31] Extracting extension completed. esbenp.prettier-vscode
[515311 ms] [01:34:32] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/streetsidesoftware.code-spell-checker-3.0.1: streetsidesoftware.code-spell-checker
[515328 ms] [01:34:32] Renamed to /home/devcontainer/.vscode-server/extensions/streetsidesoftware.code-spell-checker-3.0.1
[515334 ms] [01:34:32] Extracting extension completed. streetsidesoftware.code-spell-checker
[517810 ms] [01:34:34] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/ymotongpoo.licenser-1.10.0: ymotongpoo.licenser
[517831 ms] [01:34:35] Renamed to /home/devcontainer/.vscode-server/extensions/ymotongpoo.licenser-1.10.0
[517834 ms] [01:34:35] Extracting extension completed. ymotongpoo.licenser
[517889 ms] [01:34:35] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/ms-python.python-2024.4.1: ms-python.python
[517894 ms] [01:34:35] Renamed to /home/devcontainer/.vscode-server/extensions/ms-python.python-2024.4.1
[517904 ms] [01:34:35] Extracting extension completed. ms-python.python
[519536 ms] [01:34:36] Extension signature is verified: ms-python.debugpy
[519607 ms] [01:34:36] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/ms-python.vscode-pylance-2024.4.1: ms-python.vscode-pylance
[519626 ms] [01:34:36] Renamed to /home/devcontainer/.vscode-server/extensions/ms-python.vscode-pylance-2024.4.1
[519632 ms] [01:34:36] Extracting extension completed. ms-python.vscode-pylance
[519805 ms] [01:34:36] Extracted extension to file:///home/devcontainer/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64: ms-python.debugpy
[519808 ms] [01:34:36] Renamed to /home/devcontainer/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64
[519812 ms] [01:34:36] Extracting extension completed. ms-python.debugpy
[519816 ms] [01:34:36] Rollback: Uninstalling installed extensions Unable to write file '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json')
[519821 ms] [01:34:36] Rollback: Uninstalled extension stylelint.vscode-stylelint
[519823 ms] [01:34:36] Marked extension as uninstalled stylelint.vscode-stylelint-1.4.0
[519824 ms] [01:34:36] Rollback: Uninstalled extension dbaeumer.vscode-eslint
[519827 ms] [01:34:37] Rollback: Uninstalled extension shardulm94.trailing-spaces
[519828 ms] [01:34:37] Marked extension as uninstalled dbaeumer.vscode-eslint-2.4.4
[519831 ms] [01:34:37] Marked extension as uninstalled shardulm94.trailing-spaces-0.4.1
[519832 ms] [01:34:37] Rollback: Uninstalled extension ms-azuretools.vscode-docker
[519853 ms] [01:34:37] Rollback: Uninstalled extension esbenp.prettier-vscode
[519854 ms] [01:34:37] Marked extension as uninstalled ms-azuretools.vscode-docker-1.29.0
[519858 ms] [01:34:37] Marked extension as uninstalled esbenp.prettier-vscode-10.4.0
[519858 ms] [01:34:37] Rollback: Uninstalled extension streetsidesoftware.code-spell-checker
[519864 ms] [01:34:37] Rollback: Uninstalled extension ymotongpoo.licenser
[519865 ms] [01:34:37] Marked extension as uninstalled streetsidesoftware.code-spell-checker-3.0.1
[519868 ms] [01:34:37] Marked extension as uninstalled ymotongpoo.licenser-1.10.0
[519869 ms] [01:34:37] Rollback: Uninstalled extension ms-python.python
[519875 ms] [01:34:37] Rollback: Uninstalled extension ms-python.vscode-pylance
[519875 ms] [01:34:37] Marked extension as uninstalled ms-python.python-2024.4.1
[519879 ms] [01:34:37] Rollback: Uninstalled extension ms-python.debugpy
[519881 ms] [01:34:37] Error while installing extensions: Unable to write file '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json')
[519884 ms] [01:34:37] UpdateMetadata: Unable to write file '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/extensions/ms-vscode.js-debug/package.json')
    at se.x (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:173:82669)
    at async se.h (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:173:80430) {
  code: 'UpdateMetadata'
}
[519887 ms] [01:34:37] Marked extension as uninstalled ms-python.vscode-pylance-2024.4.1
[519891 ms] [01:34:37] Marked extension as uninstalled ms-python.debugpy-2024.4.0-linux-x64
[519952 ms] [01:34:37] Deleted uninstalled extension from disk stylelint.vscode-stylelint /home/devcontainer/.vscode-server/extensions/stylelint.vscode-stylelint-1.4.0
[520018 ms] [01:34:37] Deleted uninstalled extension from disk dbaeumer.vscode-eslint /home/devcontainer/.vscode-server/extensions/dbaeumer.vscode-eslint-2.4.4
[01:34:37] Deleted uninstalled extension from disk esbenp.prettier-vscode /home/devcontainer/.vscode-server/extensions/esbenp.prettier-vscode-10.4.0
[520190 ms] [01:34:37] Deleted uninstalled extension from disk shardulm94.trailing-spaces /home/devcontainer/.vscode-server/extensions/shardulm94.trailing-spaces-0.4.1
[520260 ms] [01:34:37] Deleted uninstalled extension from disk ms-azuretools.vscode-docker /home/devcontainer/.vscode-server/extensions/ms-azuretools.vscode-docker-1.29.0
[520266 ms] [01:34:37] Deleted uninstalled extension from disk streetsidesoftware.code-spell-checker /home/devcontainer/.vscode-server/extensions/streetsidesoftware.code-spell-checker-3.0.1
[520310 ms] [01:34:37] Deleted uninstalled extension from disk ymotongpoo.licenser /home/devcontainer/.vscode-server/extensions/ymotongpoo.licenser-1.10.0
[520321 ms] [01:34:37] Deleted uninstalled extension from disk ms-python.vscode-pylance /home/devcontainer/.vscode-server/extensions/ms-python.vscode-pylance-2024.4.1
[520322 ms] [01:34:37] Deleted uninstalled extension from disk ms-python.python /home/devcontainer/.vscode-server/extensions/ms-python.python-2024.4.1
[521317 ms] rejected promise not handled within 1 second: EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/devcontainer/.vscode-server/extensions/shardulm94.trailing-spaces-0.4.1.-4aa54e65.vsctmp'
[521319 ms] stack trace: EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/devcontainer/.vscode-server/extensions/shardulm94.trailing-spaces-0.4.1.-4aa54e65.vsctmp'
    at n.create (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:114:29480)
    at b (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:114:29595)
    at t.fb (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:119:35526)
    at t.stat (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:119:27972)
    at async l.stat (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:119:15117)
    at async x.sb (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:173:71576)
[01:34:38] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/devcontainer/.vscode-server/extensions/shardulm94.trailing-spaces-0.4.1.-4aa54e65.vsctmp'
    at n.create (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:114:29480)
    at b (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:114:29595)
    at t.fb (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:119:35526)
    at t.stat (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:119:27972)
    at async l.stat (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:119:15117)
    at async x.sb (/vscode/vscode-server/bin/linux-x64/5c3e652f63e798a5ac2f31ffd0d863669328dc4c/out/vs/server/node/server.main.js:173:71576) {
  code: 'EntryNotFound'
}

VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:25:57.039Z)
OS version: Linux x64 6.8.2-arch2-1
Modes:
Remote OS version: Linux x64 6.8.2-arch2-1

**Comment by madhurivadaligithub** [comment]
Hi @g-kartik 
Thanks for reaching VS Marketplace Team, could you please share extension and publisher details for us to investigate better.

Also could please contact the publisher owner's through QnA for extension related queries.

-VS Marketplace Team

**Comment by g-kartik** [comment]
Sometimes some of them, at other times, are all of them.

Working in Insiders. It is fixed I guess.
