### ISSUE TITLE
Error while installing 'Material Icon Theme' extension. Please check the log for more details.

### ISSUE THREAD

**Issue by Sab2020** [microsoft/vsmarketplace#93]
Issue Type: <b>Bug</b>

[2021-06-03 20:51:47.918] [renderer1] [error] net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH: Error: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:109:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
[2021-06-03 20:52:49.837] [renderer1] [error] XHR timeout: undefinedms: downloading: XHR timeout: undefinedms
    at G.downloadInstallableExtension (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:197630)
    at async G.doInstallFromGallery (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:195025)
[2021-06-03 20:59:09.672] [renderer1] [error] ["downloading: XHR timeout: undefinedms","    at G.downloadInstallableExtension (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:197630)","    at async G.doInstallFromGallery (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:195025)"]
[2021-06-03 20:59:09.697] [renderer1] [error] XHR timeout: undefinedms: downloading: XHR timeout: undefinedms
    at G.downloadInstallableExtension (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:197630)
    at async G.doInstallFromGallery (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:195025)
[2021-06-03 20:59:53.035] [renderer1] [error] ["downloading: XHR timeout: undefinedms","    at G.downloadInstallableExtension (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:197630)","    at async G.doInstallFromGallery (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:195025)"]
[2021-06-03 20:59:53.072] [renderer1] [error] XHR timeout: undefinedms: downloading: XHR timeout: undefinedms
    at G.downloadInstallableExtension (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:197630)
    at async G.doInstallFromGallery (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:195025)
[2021-06-03 21:00:17.768] [renderer1] [error] Error: XHR timeout: undefinedms
    at XMLHttpRequest.w.ontimeout (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:24696)
[2021-06-03 21:00:17.806] [renderer1] [error] XHR timeout: undefinedms: Error: XHR timeout: undefinedms
    at XMLHttpRequest.w.ontimeout (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:24696)
[2021-06-03 21:00:26.202] [renderer1] [error] Error: XHR timeout: undefinedms
    at XMLHttpRequest.w.ontimeout (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:24696)
[2021-06-03 21:01:17.941] [renderer1] [error] Error: XHR timeout: undefinedms
    at XMLHttpRequest.w.ontimeout (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:24696)
[2021-06-03 21:01:17.968] [renderer1] [error] XHR timeout: undefinedms: Error: XHR timeout: undefinedms
    at XMLHttpRequest.w.ontimeout (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:24696)
[2021-06-03 21:01:34.309] [renderer1] [error] Error: XHR timeout: undefinedms
    at XMLHttpRequest.w.ontimeout (file:///C:/Users/Kargadan/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:76:24696)

VS Code version: Code - Insiders 1.57.0-insider (20df87725d3ce4a501187f0240c2f159aa0ad2a5, 2021-06-03T06:38:36.085Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
This is a VS Code issue it seems, feel free to open an issue in the VS Code repo.
Nothing Marketplace can do
